Hib 121 hyp3 process module
asfadmin/hyp3-in-a-box pull request #111
Opened 2018-08-03 00:46 UTC by williamh890

## TODO

- [x] Turn `processes/rtc_snap` into module
- [x] Remove rtc_specific stuff
- [x] Have rtc_process use new `hyp3_process` module
- [ ] Module documentation

## Next

-  Integrate with ec2/worker code
-  Have `hyp3_process` take generic processing job
-  Exposes mocked version of hyp3_process decorator for processes to use for testing (similar to boto3 dry run)
-  Add some logging within the `hyp3_process` module 
-  Figure out infrastructure (ec2 config)

2018-08-03 22:36 UTC, Askaholic requested changes

2018-08-03 22:36 UTC, Askaholic commented on modules/hyp3_process/setup.py
> +                 " around processing scripts"),
super nit picky and doesn't really matter, but I usually would prefer to put the space at the end of the first line so that the words on the second line up nicely...

2018-08-03 22:36 UTC, Askaholic commented on modules/hyp3_process/test/import_rtc_snap.py
> +    sys.path.append(str(path))
All these files are exactly the same, and I think we should make all the code be exactly the same too. We should pick one of the implementations, either the pathlib or the plain string one and drop it in all the files.

2018-08-03 22:36 UTC, Askaholic commented on processes/rtc_snap/test/earthdata-creds.json
> +{"username": "wbhorn", "password": "Septov09&"}
Don't think you want to be committing this. You should change your password, and optionally purge this from the repo history (just don't screw up!)

2018-08-06 15:57 UTC, williamh890 commented on processes/rtc_snap/test/earthdata-creds.json
> +{"username": "wbhorn", "password": "Septov09&"}
Lol, thx

2018-08-06 16:03 UTC, williamh890 commented on modules/hyp3_process/test/import_rtc_snap.py
> +    sys.path.append(str(path))
Agreed

2018-08-06 16:43 UTC, Askaholic approved these changes

2018-08-06 16:44 UTC, merged