Hib 188 ec2 working integration
asfadmin/hyp3-in-a-box pull request #122
Opened 2018-08-06 23:59 UTC by williamh890

## TODO
- [x] Input ssm param names using user data
- [x] Pull param names from ssm
- [x] hyp3 worker using handler function
- [x] Call handlers using naming convension
- [x] Entry point for process (/ec2/worker)
- [ ] e2e test of hyp3_process module on ec2 instance

2018-08-07 23:27 UTC, Askaholic requested changes

2018-08-07 23:27 UTC, Askaholic commented on modules/hyp3_process/src/hyp3_process/hyp3_daemon/hyp3_daemon.py
> +        self.previous_worker_status = WS.NO_STATUS
Shortening names because no text completion?

2018-08-07 23:27 UTC, Askaholic commented on modules/hyp3_process/src/hyp3_process/hyp3_daemon/hyp3_daemon.py
> +        self.previous_worker_status = WS.NO_STATUS
I disapprove

2018-08-07 23:27 UTC, Askaholic commented on modules/hyp3_process/src/hyp3_process/hyp3_daemon/hyp3_daemon.py
> +def make_email_event_from(job):
Might as well not use Objects anymore if you're going to go down this road

2018-08-07 23:27 UTC, Askaholic commented on modules/hyp3_process/src/hyp3_process/hyp3_daemon/hyp3_worker.py
> +# hyp3_worker.py
Can probably remove the hyp3_ prefix if its going to live in a hyp3_daemon sub directory

2018-08-07 23:27 UTC, Askaholic commented on modules/hyp3_process/src/hyp3_process/hyp3_daemon/services/__init__.py
> +    MAX_MESSAGES = 1
This will never be a value other than 1. It's the equivalent of refactoring a constant called `ONE = 1`, except for with about 3 times as many characters.

2018-08-07 23:27 UTC, Askaholic commented on modules/hyp3_process/src/hyp3_process/hyp3_daemon/services/__init__.py
> +            log.info('no messages found')
I really don't think we want "no messages found" to be printed in the log files every second for every worker that's idle

2018-08-07 23:27 UTC, Askaholic commented on modules/hyp3_process/src/hyp3_process/hyp3_handler.py
> +import asf_granule_util as gu
from asf_granule_util import SentinelGranule

2018-08-07 23:27 UTC, Askaholic commented on modules/hyp3_process/src/hyp3_process/hyp3_process.py
> +        print(args)
Logger can be used here

2018-08-07 23:55 UTC, williamh890 commented on modules/hyp3_process/src/hyp3_process/hyp3_daemon/services/__init__.py
> +    MAX_MESSAGES = 1
This value is used in 2 places. 

Plus makes this line more readable.
```python
55| if len(messages) > self.MAX_MESSAGES:
```

2018-08-07 23:57 UTC, williamh890 commented on modules/hyp3_process/src/hyp3_process/hyp3_daemon/hyp3_daemon.py
> +def make_email_event_from(job):
Did this because it was easier to mock EmailEvent creation

2018-08-07 23:57 UTC, williamh890 commented on modules/hyp3_process/src/hyp3_process/hyp3_daemon/hyp3_daemon.py
> +        self.previous_worker_status = WS.NO_STATUS
Fair

2018-08-08 00:39 UTC, Askaholic commented on modules/hyp3_process/src/hyp3_process/hyp3_daemon/services/__init__.py
> +    MAX_MESSAGES = 1
It actually makes it less readable, because it implies that the length could be greater than 1. In this case the constant 1 is actually just the constant 1 and it will always be 1. It's only necessary because boto3 always returns a list, even if you request only 1 item. This check will only ever be true if there is a bug in boto3 we could probably safely remove it, but I like thinking about possible places errors could occur and handling them elegantly.

2018-08-08 00:48 UTC, Askaholic commented on modules/hyp3_process/src/hyp3_process/hyp3_daemon/hyp3_daemon.py
> +def make_email_event_from(job):
`@mock.patch('hyp3_events.EmailEvent')`

2018-08-08 16:30 UTC, Askaholic approved these changes

2018-08-08 16:33 UTC, merged